#pragma once

#define VERSION "1.0.4"
#define DEVELOPER_PAGE "https://github.com/kyt9601/PROJECT_REVERSI"

#define BOARD_SIZE 8
#define COMPUTER_SLEEP_TIME_MS 500
#define WAITING_SECONDS 5

enum STATUS{ENUM_WHITE, ENUM_BLACK, ENUM_EMPTY, ENUM_BOUND};
enum RESULT{ENUM_INIT,
			ENUM_WIN_EASY, ENUM_LOSE_EASY, ENUM_DRAW_EASY,
			ENUM_WIN_NORMAL, ENUM_LOSE_NORMAL, ENUM_DRAW_NORMAL,
			ENUM_WIN_HARD, ENUM_LOSE_HARD, ENUM_DRAW_HARD,
			ENUM_WIN_EXPERT, ENUM_LOSE_EXPERT, ENUM_DRAW_EXPERT,
			ENUM_WIN_MASTER, ENUM_LOSE_MASTER, ENUM_DRAW_MASTER};
